name: PKUAutoSubmit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '18 22 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yousiki/PKUAutoSubmit-action@master
        with:
          username: ${{ secrets.dusername }}
          password: ${{ secrets.dpassword }}
          reason: ${{ secrets.reason }}
          wechat: "False"
          sckey: ${{ secrets.sckey }}
